package view;

import view.PacienteView;
import view.ProfissionalSaudeView;
import view.VacinaView;

public class InterfacePrincipal extends javax.swing.JFrame {

    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jButtonPacientes = new javax.swing.JButton();
        jButtonProfissionais = new javax.swing.JButton();
        jButtonVacinas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuInfo = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setFont(new java.awt.Font("Liberation Sans", 3, 48)); // NOI18N
        jLabelNome.setText("VacSolution");

        jButtonPacientes.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonPacientes.setText("Pacientes");
        jButtonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacientesActionPerformed(evt);
            }
        });

        jButtonProfissionais.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonProfissionais.setText("Profissionais de Saude");
        jButtonProfissionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfissionaisActionPerformed(evt);
            }
        });

        jButtonVacinas.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonVacinas.setText("Vacina");
        jButtonVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVacinasActionPerformed(evt);
            }
        });

        jMenuArquivo.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuArquivo.setText("Arquivo");
        jMenuBar1.add(jMenuArquivo);

        jMenuEditar.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuEditar.setText("Editar");
        jMenuBar1.add(jMenuEditar);

        jMenuInfo.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuInfo.setText("Informações");
        jMenuBar1.add(jMenuInfo);

        jMenuSair.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuSair.setText("Sair");
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabelNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButtonPacientes)
                        .addGap(137, 137, 137)
                        .addComponent(jButtonProfissionais))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jButtonVacinas)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabelNome)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPacientes)
                    .addComponent(jButtonProfissionais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonVacinas)
                .addGap(119, 119, 119))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacientesActionPerformed
        new PacienteView();
        PacienteView cadastroPaciente = new PacienteView();
        cadastroPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPacientesActionPerformed

    private void jButtonProfissionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfissionaisActionPerformed
        new ProfissionalSaudeView();
        ProfissionalSaudeView cadastroProfissional = new ProfissionalSaudeView();
        cadastroProfissional.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProfissionaisActionPerformed

    private void jButtonVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVacinasActionPerformed
        new VacinaView();
        VacinaView cadastroVacina = new VacinaView();
        cadastroVacina.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVacinasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPacientes;
    private javax.swing.JButton jButtonProfissionais;
    private javax.swing.JButton jButtonVacinas;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
